### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by sgrove** [kovasb/gamma-driver#4]
Initially reported here: https://github.com/sgrove/gamma-playground/issues/10

```
I am seeing some warnings when executing (run) and (browser-repl):

WARNING: mask already refers to: /mask being replaced by: gamma-driver.common.draw/mask at line 7 file:/Users/mac/.m2/repository/kovasb/gamma-driver/0.1.0-SNAPSHOT/gamma-driver-0.1.0-SNAPSHOT.jar!/gamma_driver/common/draw.cljs
```

Best to take care of this kind of thing early - people like @brandonbloom have build scripts which fail on any warning to keep things in a good state.

**Comment by brandonbloom** [comment]
I have what now?

**Comment by sgrove** [comment]
@brandonbloom I picked up the habit form you, where build scripts (e.g. for compiling production cljs) should fail on warnings.

**Comment by kovasb** [comment]
Ok this is fixed as far as gamma code is concerned. Still getting a warning from fipp https://github.com/brandonbloom/fipp/issues/25
